# Generated by Django 4.0.1 on 2022-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_weblistingtable_category_weblistingtable_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryTable',
        ),
        migrations.DeleteModel(
            name='WebListingTable',
        ),
    ]
